### ISSUE TITLE
Error when running same flag in different sub-commands

### ISSUE THREAD

**Issue by sirmar** [devfacet/gocmd#1]
When running same flag short/long name in different sub-commands I get the following error:

`short argument n in Name field is already defined in Name field`

This is some code triggering the error.
```
Create struct {
	Python struct {
		Name string `short:"n"`
	} `command:"python"`
	Golang struct {
		Name string `short:"n"`
	} `command:"golang"`
} `command:"create"`
```

Also when giving them different short flag (like m and n) the auto help puts then in the same context:

```
create
    python         
    golang         
      -m, --mame   
      -n, --name   
```
I would expect it to be possible to use the same flags within different sub-commands. Bug or by design?

Edit: Added auto-help output.

**Comment by sirmar** [comment]
Oh. The mystery deepens.

My little project involves cross-compiling. So this is my findings:
- Normal compile on linux works fine.
- Normal compile on mac works fine.
- Cross-compile on linux to a mac binary has the bug.

I build the project in an alpine golang image like this, given that an image with some golang code in it.

```
    docker run --rm \
	   -v /tmp:/go/bin \
	   -e GOOS=darwin \
	   -e GOARCH=386 \
	   meta:latest \
	   go build -o /go/bin/meta ./cmd
```

The full code is here on github: https://github.com/sirmar/meta

**Comment by sirmar** [comment]
And changing up the GOARCH to amd64 made it work.

Let's leave it with that, unless you are super into understanding why. ;o)

**Comment by devfacet** [comment]
What's the Go version? I would like to reproduce the issue and find out what's going on.

**Comment by sirmar** [comment]
I run the cross compilation in a Dockerfile based on image golang:1.9-alpine.
